version: "3"
services:
  base:
    image: {{ cookiecutter.repo_name }}
    build:
      context: .
      dockerfile: Dockerfile

  app:
    depends_on:
      - base
    image: {{ cookiecutter.repo_name }}
    container_name: "{{ cookiecutter.repo_name }}_app"
    volumes:
      - .:/app
    working_dir: /app
    command: ["pipenv", "run", "python", "main.py"]

  jupyter:
    depends_on:
      - base
    image: {{ cookiecutter.repo_name }}
    container_name: "{{ cookiecutter.repo_name }}_jupyter"
    ports:
      - "127.0.0.1:{{ cookiecutter.jupyter_port  }}:8888"
    volumes:
      - .:/app
    working_dir: /app
    command: ["pipenv", "run", "jupyter", "lab", "--ip=0.0.0.0"]
